// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


class NativeHttpRequestOhos {
  NativeHttpRequestOhos({
    required this.method,
    required this.url,
    required this.headers,
    this.body,
    this.connectTimeoutMs,
    this.readTimeoutMs,
  });

  String method;

  String url;

  Map<String, String> headers;

  Uint8List? body;

  int? connectTimeoutMs;

  int? readTimeoutMs;

  List<Object?> _toList() {
    return <Object?>[
      method,
      url,
      headers,
      body,
      connectTimeoutMs,
      readTimeoutMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeHttpRequestOhos decode(Object result) {
    result as List<Object?>;
    return NativeHttpRequestOhos(
      method: result[0]! as String,
      url: result[1]! as String,
      headers: (result[2] as Map<Object?, Object?>?)!.cast<String, String>(),
      body: result[3] as Uint8List?,
      connectTimeoutMs: result[4] as int?,
      readTimeoutMs: result[5] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeHttpRequestOhos || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class NativeHttpResponseOhos {
  NativeHttpResponseOhos({
    required this.statusCode,
    required this.headers,
    required this.body,
  });

  int statusCode;

  Map<String, String> headers;

  Uint8List body;

  List<Object?> _toList() {
    return <Object?>[
      statusCode,
      headers,
      body,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeHttpResponseOhos decode(Object result) {
    result as List<Object?>;
    return NativeHttpResponseOhos(
      statusCode: result[0]! as int,
      headers: (result[1] as Map<Object?, Object?>?)!.cast<String, String>(),
      body: result[2]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeHttpResponseOhos || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class NativeHttpStreamHeadersOhos {
  NativeHttpStreamHeadersOhos({
    this.statusCode,
    required this.headers,
  });

  int? statusCode;

  Map<String, String> headers;

  List<Object?> _toList() {
    return <Object?>[
      statusCode,
      headers,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeHttpStreamHeadersOhos decode(Object result) {
    result as List<Object?>;
    return NativeHttpStreamHeadersOhos(
      statusCode: result[0] as int?,
      headers: (result[1] as Map<Object?, Object?>?)!.cast<String, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeHttpStreamHeadersOhos || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class NativeHttpMultipartRequestOhos {
  NativeHttpMultipartRequestOhos({
    required this.method,
    required this.url,
    required this.headers,
    required this.fields,
    required this.fileFieldName,
    required this.filePath,
    required this.fileName,
    required this.contentType,
    this.connectTimeoutMs,
    this.readTimeoutMs,
  });

  String method;

  String url;

  Map<String, String> headers;

  Map<String, String> fields;

  String fileFieldName;

  String filePath;

  String fileName;

  String contentType;

  int? connectTimeoutMs;

  int? readTimeoutMs;

  List<Object?> _toList() {
    return <Object?>[
      method,
      url,
      headers,
      fields,
      fileFieldName,
      filePath,
      fileName,
      contentType,
      connectTimeoutMs,
      readTimeoutMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeHttpMultipartRequestOhos decode(Object result) {
    result as List<Object?>;
    return NativeHttpMultipartRequestOhos(
      method: result[0]! as String,
      url: result[1]! as String,
      headers: (result[2] as Map<Object?, Object?>?)!.cast<String, String>(),
      fields: (result[3] as Map<Object?, Object?>?)!.cast<String, String>(),
      fileFieldName: result[4]! as String,
      filePath: result[5]! as String,
      fileName: result[6]! as String,
      contentType: result[7]! as String,
      connectTimeoutMs: result[8] as int?,
      readTimeoutMs: result[9] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeHttpMultipartRequestOhos || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativeHttpRequestOhos) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is NativeHttpResponseOhos) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is NativeHttpStreamHeadersOhos) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is NativeHttpMultipartRequestOhos) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return NativeHttpRequestOhos.decode(readValue(buffer)!);
      case 130: 
        return NativeHttpResponseOhos.decode(readValue(buffer)!);
      case 131: 
        return NativeHttpStreamHeadersOhos.decode(readValue(buffer)!);
      case 132: 
        return NativeHttpMultipartRequestOhos.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NativeHttpApiOhos {
  /// Constructor for [NativeHttpApiOhos].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeHttpApiOhos({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<NativeHttpResponseOhos> sendRequest(NativeHttpRequestOhos request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.ohos_http.NativeHttpApiOhos.sendRequest$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NativeHttpResponseOhos?)!;
    }
  }

  Future<void> sendStreamRequest(int requestId, NativeHttpRequestOhos request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.ohos_http.NativeHttpApiOhos.sendStreamRequest$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestId, request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> cancelStreamRequest(int requestId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.ohos_http.NativeHttpApiOhos.cancelStreamRequest$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<NativeHttpResponseOhos> sendMultipartRequest(int requestId, NativeHttpMultipartRequestOhos request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.ohos_http.NativeHttpApiOhos.sendMultipartRequest$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestId, request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NativeHttpResponseOhos?)!;
    }
  }

  Future<void> cancelMultipartRequest(int requestId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.ohos_http.NativeHttpApiOhos.cancelMultipartRequest$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class NativeHttpFlutterApiOhos {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<void> onStreamHeaders(int requestId, NativeHttpStreamHeadersOhos response);

  Future<void> onStreamData(int requestId, Uint8List chunk);

  Future<void> onStreamComplete(int requestId, int statusCode);

  Future<void> onStreamError(int requestId, String code, String message);

  Future<void> onUploadProgress(int requestId, int bytesSent, int totalBytes);

  static void setUp(NativeHttpFlutterApiOhos? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamHeaders$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamHeaders was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_requestId = (args[0] as int?);
          assert(arg_requestId != null,
              'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamHeaders was null, expected non-null int.');
          final NativeHttpStreamHeadersOhos? arg_response = (args[1] as NativeHttpStreamHeadersOhos?);
          assert(arg_response != null,
              'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamHeaders was null, expected non-null NativeHttpStreamHeadersOhos.');
          try {
            await api.onStreamHeaders(arg_requestId!, arg_response!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamData$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamData was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_requestId = (args[0] as int?);
          assert(arg_requestId != null,
              'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamData was null, expected non-null int.');
          final Uint8List? arg_chunk = (args[1] as Uint8List?);
          assert(arg_chunk != null,
              'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamData was null, expected non-null Uint8List.');
          try {
            await api.onStreamData(arg_requestId!, arg_chunk!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamComplete$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamComplete was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_requestId = (args[0] as int?);
          assert(arg_requestId != null,
              'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamComplete was null, expected non-null int.');
          final int? arg_statusCode = (args[1] as int?);
          assert(arg_statusCode != null,
              'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamComplete was null, expected non-null int.');
          try {
            await api.onStreamComplete(arg_requestId!, arg_statusCode!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_requestId = (args[0] as int?);
          assert(arg_requestId != null,
              'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamError was null, expected non-null int.');
          final String? arg_code = (args[1] as String?);
          assert(arg_code != null,
              'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamError was null, expected non-null String.');
          final String? arg_message = (args[2] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onStreamError was null, expected non-null String.');
          try {
            await api.onStreamError(arg_requestId!, arg_code!, arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onUploadProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onUploadProgress was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_requestId = (args[0] as int?);
          assert(arg_requestId != null,
              'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onUploadProgress was null, expected non-null int.');
          final int? arg_bytesSent = (args[1] as int?);
          assert(arg_bytesSent != null,
              'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onUploadProgress was null, expected non-null int.');
          final int? arg_totalBytes = (args[2] as int?);
          assert(arg_totalBytes != null,
              'Argument for dev.flutter.pigeon.ohos_http.NativeHttpFlutterApiOhos.onUploadProgress was null, expected non-null int.');
          try {
            await api.onUploadProgress(arg_requestId!, arg_bytesSent!, arg_totalBytes!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
